### ISSUE TITLE
train.py [SyntaxError: invalid syntax] & visdom [No such file or directory]

### ISSUE THREAD

**Issue by deepseek** [mrluin/ESFNet-Pytorch#3]
@mrluin Thank you for your hard work,

When running the training commands that you stated, I get error messages:
 
```
(esfnet) home@home-desktop:~/programs/ESFNet$ python -m visdom.server -env_path='./visdom_log' -port=8098 # start visdom server
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/visdom/server.py", line 1218, in start_server
    readonly=readonly, user_credential=user_credential)
  File "/home/home/anaconda3/envs/esfnet/lib/python3.6/site-packages/visdom/server.py", line 145, in __init__
    env_jsons = [i for i in os.listdir(env_path) if '.json' in i]
FileNotFoundError: [Errno 2] No such file or directory: './visdom_log'
```

Also when running train.py:
```
(esfnet) home@home-desktop:~/programs/ESFNet$ python train.py
  File "train.py", line 58
    ,)
    ^
SyntaxError: invalid syntax
```

**Comment by mrluin** [comment]
Hi @deepseek ,
For the problem of the first code snippet, the directory of the log of visdom should under `/ESFNet` in your case, like `/ESFNet/visdom_log`. Thus you could call `./visdom_log` under the directory of `/ESFNet`.

**Comment by deepseek** [comment]
@mrluin merge my pull request, then close this issue.
